In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [4]:
import numpy as np

output = np.array([0.4,0.5], ndmin=2).T
e = np.array([0.8,0.5], ndmin=2)
W_hidden = np.array([[2.0,1.0],[3.0,4.0]]).T

func = lambda x : 1/(1+np.exp(-x))

Wout_sum = np.dot(W_hidden,output)
print("시그모이드 함수 내의 합\n", Wout_sum)

sig = func(Wout_sum)
print("시그모이드 함수의 값\n", sig)

시그모이드 함수 내의 합
 [[2.3]
 [2.4]]
시그모이드 함수의 값
 [[0.90887704]
 [0.9168273 ]]


In [10]:
one_sig = 1-sig

hidden_outpunt = np.array([0.4,0.5], ndmin=2)

mul_sig = sig*one_sig
print("두번째 항의 값\n",mul_sig)

두번째 항의 값
 [[0.08281957]
 [0.076255  ]]


In [15]:
first = e.T* mul_sig
print("오차 * 두번째 항\n", first)

오차 * 두번째 항
 [[0.06625565]
 [0.0381275 ]]


In [17]:
gradient = -np.dot(first,output.T).T
print("오차 기울기\n", gradient)

change = 0.1 * gradient
print("변화량\n", change)

오차 기울기
 [[-0.02650226 -0.015251  ]
 [-0.03312783 -0.01906375]]
변화량
 [[-0.00265023 -0.0015251 ]
 [-0.00331278 -0.00190637]]


In [21]:
new_w = W_hidden-change
print("새로운 w\n", new_w)
# w11, w12
# w21, w22

새로운 w
 [[2.00265023 3.0015251 ]
 [1.00331278 4.00190637]]
