In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [7]:
import numpy as np

Winput_hidden = np.array([[3.0,2.0],[1.0,7.0]], ndmin=2)
print("Winput_hidden\n", Winput_hidden)

Whidden_output = np.array([[2.0,3.0],[1.0,4.0]], ndmin=2)
print("Whidden_output\n", Whidden_output)

Eoutput= np.array([0.8,0.5], ndmin=2).T
print("Eoutput\n", Eoutput)
print("Eoutput.sum\n", Eoutput.sum())

Whidden_output_sum1 = Whidden_output.sum(axis=1, dtype='float')
Whidden_output_norm = Whidden_output.T/Whidden_output_sum1
print("Whidden_output_sum1\n", Whidden_output_sum1)
print("Whidden_output_norm\n", Whidden_output_norm)

Ehidden = np.dot(Whidden_output_norm, Eoutput)
print("Ehidden\n", Ehidden)
print("Ehidden.sum\n", Ehidden.sum())


Winput_hidden_sum1 = Winput_hidden.sum(axis = 1, dtype = 'float')
Winput_hidden_norm = Winput_hidden.T/Winput_hidden_sum1.T
print("Winput_hidden_sum1\n", Winput_hidden_sum1)
print("Winput_hidden_norm\n", Winput_hidden_norm)

Einput= np.dot(Winput_hidden_norm, Ehidden)
print("Einput\n", Einput)
print("Einput.sum\n", Einput.sum())

Winput_hidden
 [[3. 2.]
 [1. 7.]]
Whidden_output
 [[2. 3.]
 [1. 4.]]
Eoutput
 [[0.8]
 [0.5]]
Eoutput.sum
 1.3
Whidden_output_sum1
 [5. 5.]
Whidden_output_norm
 [[0.4 0.2]
 [0.6 0.8]]
Ehidden
 [[0.42]
 [0.88]]
Ehidden.sum
 1.3
Winput_hidden_sum1
 [5. 8.]
Winput_hidden_norm
 [[0.6   0.125]
 [0.4   0.875]]
Einput
 [[0.362]
 [0.938]]
Einput.sum
 1.3
