In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [4]:
import numpy as np

activation_function = lambda x: 1/ (1 + np.exp(-x))

Winput_hidden = np.array([[0.9,0.3,0.4],[0.2,0.8,0.2],[0.1,0.5,0.6]])
print("[Winput_hidden]\n", Winput_hidden)

Woutput_hidden = np.array([[0.3,0.7,0.5],[0.6,0.5,0.2],[0.8,0.1,0.9]])
print("[Woutput_hidden]\n", Woutput_hidden)

input = np.array([0.9,0.1,0.8], ndmin=2).T
print("[input]\n", input)

Xhidden = np.dot(Winput_hidden, input)
print("[Xhidden]\n", Xhidden)

Ohidden = activation_function(Xhidden)
print("[Ohidden]\n", Ohidden)

Xoutput = np.dot(Woutput_hidden,Ohidden)
print("[Xoutput]\n", Xoutput)

output = activation_function(Xoutput)
print("[output]\n", output)

[Winput_hidden]
 [[0.9 0.3 0.4]
 [0.2 0.8 0.2]
 [0.1 0.5 0.6]]
[Woutput_hidden]
 [[0.3 0.7 0.5]
 [0.6 0.5 0.2]
 [0.8 0.1 0.9]]
[input]
 [[0.9]
 [0.1]
 [0.8]]
[Xhidden]
 [[1.16]
 [0.42]
 [0.62]]
[Ohidden]
 [[0.76133271]
 [0.60348325]
 [0.65021855]]
[Xoutput]
 [[0.97594736]
 [0.88858496]
 [1.25461119]]
[output]
 [[0.72630335]
 [0.70859807]
 [0.77809706]]
