In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import numpy as np

target = np.array([[0.01],[0.01],[0.99]])

activation_function = lambda x: 1/ (1 + np.exp(-x))

Winput_hidden = np.array([[0.9,0.3,0.4],[0.2,0.8,0.2],[0.1,0.5,0.6]])
Woutput_hidden = np.array([[0.3,0.7,0.5],[0.6,0.5,0.2],[0.8,0.1,0.9]])

input = np.array([0.9,0.1,0.8], ndmin=2).T
Xhidden = np.dot(Winput_hidden, input)
Ohidden = activation_function(Xhidden)
Xoutput = np.dot(Woutput_hidden,Ohidden)
output = activation_function(Xoutput)

In [3]:
output

array([[0.72630335],
       [0.70859807],
       [0.77809706]])

In [11]:
e = target-output
print("Eoutput\n",e)

Whidden_output_sum1 = Woutput_hidden.sum(axis=1, dtype='float')
Whidden_output_norm = Woutput_hidden.T/Whidden_output_sum1
print("Whidden_output_sum1\n", Whidden_output_sum1)
print("Whidden_output_norm\n", Whidden_output_norm)

Eoutput
 [[-0.71630335]
 [-0.69859807]
 [ 0.21190294]]
Whidden_output_sum1
 [1.5 1.3 1.8]
Whidden_output_norm
 [[0.2        0.46153846 0.44444444]
 [0.46666667 0.38461538 0.05555556]
 [0.33333333 0.15384615 0.5       ]]


In [12]:
Ehidden = np.dot(Whidden_output_norm, e)
print("Ehidden\n", Ehidden)
print("Ehidden.sum\n", Ehidden.sum())

Ehidden
 [[-0.37151146]
 [-0.59119408]
 [-0.24029294]]
Ehidden.sum
 -1.2029984769999442


# ↑은닉계층의 역전파 오차 값

# ↓은닉계층의 가중치들의 업데이트

In [13]:
sigma = np.dot(Woutput_hidden, output)
print("시그모이드 함수 내의 합\n", sigma)

sigmoid = activation_function(sigma)
print("시그모이드 함수의 값\n", sigmoid)

시그모이드 함수 내의 합
 [[1.10295818]
 [0.94570046]
 [1.35218984]]
시그모이드 함수의 값
 [[0.75081397]
 [0.72024968]
 [0.79448741]]


In [14]:
one_sig = 1-sigmoid

In [15]:
mul_sig = sigmoid*one_sig
print("두번째 항의 값\n",mul_sig)

first = e*mul_sig
print("오차 * 두번째 항\n", first)

gradient = -np.dot(first,output.T)
print("오차 기울기\n", gradient)

change = 0.1 * gradient
print("변화량\n", change)


new_w = Woutput_hidden-change
print("새로운 w\n", new_w)
# w11, w21, w31
# w12, w22, w23
# w13, w23, w33

두번째 항의 값
 [[0.18709235]
 [0.20149008]
 [0.16327717]]
오차 * 두번째 항
 [[-0.13401488]
 [-0.14076058]
 [ 0.03459891]]
오차 기울기
 [[ 0.09733545  0.09496268  0.10427658]
 [ 0.10223488  0.09974268  0.10952539]
 [-0.02512931 -0.02451672 -0.02692131]]
변화량
 [[ 0.00973355  0.00949627  0.01042766]
 [ 0.01022349  0.00997427  0.01095254]
 [-0.00251293 -0.00245167 -0.00269213]]
새로운 w
 [[0.29026645 0.69050373 0.48957234]
 [0.58977651 0.49002573 0.18904746]
 [0.80251293 0.10245167 0.90269213]]
