In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import numpy as np

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [5]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [13]:
f1 = (lambda x : x**2)
f2 = (lambda x : x**3 + x**2 + x)
f3 = (lambda x : x*np.sin(x*x*x+3))
f4 = (lambda x : np.cos(sqrt(np.exp(x)+1)/2))

In [17]:
f1(2)


4

In [16]:
f2(2)

14